// module.exports = {
//     lang:{
//         name:"xiaomixiaomi",
//         message:"This is a Xiao"
//     }
// }

// 英文
export const lang = {
  name: 'Pizza, pizza',
  message: 'This is pizza',
  home: 'Home',
  trade: 'Trade',
  exchange: 'Exchange',
  farm: 'Farm',
  castle: 'Castle',
  connectPurse: 'connectPurse',
  inviteConnect: 'InviteConnect',
  download: 'download',
  whitePaper: 'whitePaper',
  officialNews: 'officialNews',
  // 农场
  // farm: 'farm',
  raise: 'raise a pool of liquidity',
  earnProfit: 'token to earn a profit',
  pledgeToDig: 'pledge to dig',
  deposit: 'deposit',
  obtain: 'obtain',
  annualInterestRate: 'annual interest rate',
  dailyProduction: 'daily production',
  choose: 'choose',
  registered: 'registered',
  RegisteredSuc: 'Registered successfully',
  //城堡
  dailyProduction: 'daily production',
  grades: 'My grades',
  pledge: 'pledge',
  pledgePerformance: 'Pledge performance',
  personalPledge: 'Market value of personal pledge',
  upgrade: 'Not close to an upgrade',
  shareMining: 'Share the proceeds of mining',
  addresses: 'Number of coin addresses',
  a: 'a',
  no: 'no',
  soldiers: 'soldiers',
  knight: 'knight',
  fortress: 'fortress',
  duke: 'duke',
  general: 'general',
  king: 'king',
  queen: 'queen',
  maximum: 'maximum',
  authorization: 'authorization',
  available: 'available',
  extract: 'extract',

  pledged: 'pledged',
  harvestRedeem: 'Harvest and redeem',
  pledgeToDig: 'pledge to dig',
  pleaseEnter:' Please enter',

  authorizationSuc: 'Authorization success',
  userReject: 'The user rejects the transaction signature',
  pleaseAuthorize: 'Please authorize',
  pledgeSuc: 'The pledge success',
  pledgeFail: 'The pledge failure',
  toBeSuccessful: 'To be successful',
  harvestSuc: 'Harvest success',
  harvestFail: 'Harvest failure',
}
