// 日语
export const lang = {
  name: 'ピザピザ',
  message: 'これはピザです',
  home: '家',
  trade: '貿易',
  exchange: '両替',
  farm: '農場',
  castle: '城',
  connectPurse: '財布をつなぐ',
  inviteConnect: '招待接続',
  download: 'ダウンロード',
  whitePaper: '白書',
  officialNews: '公式のニュース',
  // 农场
  // farm: '農場',
  raise: '流動性プールを作りましょう',
  earnProfit: 'トークンで収益を得る',
  pledgeToDig: '採掘を保証する',
  deposit: '入金',
  obtain: '取得',
  annualInterestRate: 'ねんか金利',
  dailyProduction: '毎日生産量',
  choose: '選択',
  registered: '登録',
  RegisteredSuc: '登録成功',
  //城堡
  dailyProduction: '1日当たり総生産高',
  grades: '私のランク',
  pledge: '役員',
  pledgePerformance: '実績を担保する',
  personalPledge: '個人の時価総額です',
  upgrade: 'グレードアップまではまだまだだ',
  shareMining: 'マイニング収益を分配する',
  addresses: '所持コイン数',
  a: 'つ',
  no: '無',
  soldiers: '兵士',
  knight: '骑士',
  fortress: '砦',
  duke: '公爵',
  general: '将軍',
  king: '王',
  queen: '皇后',
  maximum: '最大値',
  authorization: 'ライセンス',
  available: '可用',
  extract: '引き出し',

  pledged: '既に身柄を確保した',
  harvestRedeem: '採掘を保証する',
  pledgeToDig: '採掘を保証する',
  pleaseEnter: '入力してください',

  authorizationSuc: '授権が成功する',
  userReject: 'ユーザはトランザクション署名を拒否する',
  pleaseAuthorize: '先に許可してください',
  pledgeSuc: '身柄引き渡しに成功した',
  pledgeFail: '留置に失敗する',
  toBeSuccessful: '成功を収める',
  harvestSuc: '収穫に成功する',
  harvestFail: '収穫失敗',
  extractSuc: '抽出に成功する',
  extractFail: '失敗の抽出',
}
