// 俄语
export const lang = {
  name: 'пицца',
  message: 'Это пицца',
  home: 'дом',
  trade: 'торговл',
  exchange: 'обм',
  farm: 'ферм',
  castle: 'замок',
  connectPurse: 'Соединительный кошелек',
  inviteConnect: 'Приглашение.',
  download: 'загрузк',
  whitePaper: 'Белая книга.',
  officialNews: 'Официально',
  // 农场
  // farm: '农场',
  raise: 'Собирайте бассейны с ликвидными средствами',
  earnProfit: 'Жетоны, чтобы получить прибыль',
  pledgeToDig: 'Под стражей',
  deposit: 'на',
  obtain: 'Доступ к',
  annualInterestRate: 'Годовая процентная ставка',
  dailyProduction: 'Ежедневная продукция',
  choose: 'выбор',
  registered: 'зарегистрирова',
  RegisteredSuc: 'Регистрация прошла успешно.',
  //城堡
  dailyProduction: 'Production journalière totale',
  grades: 'Mon grade',
  pledge: 'залог',
  pledgePerformance: 'Performance du nantissement',
  personalPledge: 'Valeur marchande du nantissement individuel',
  upgrade: 'Pas assez loin de la mise à niveau',
  shareMining: 'Partage du produit de l’arrachage',
  addresses: 'Nombre d’adresses du titulaire',
  a: 'mois',
  no: 'sans',
  soldiers: 'soldiers',
  knight: 'knight',
  fortress: 'fortress',
  duke: 'duke',
  general: 'general',
  king: 'king',
  queen: 'queen',
  maximum: 'Максимум.',
  authorization: 'разрешен',
  available: 'доступн',
  extract: 'эвакуац',

  pledged: 'Под стражей.',
  harvestRedeem: 'Забрать и выкупить',
  pledgeToDig: 'Под стражей',
  pleaseEnter: 'Входите.',

  authorizationSuc: 'Разрешение получено.',
  userReject: 'Пользователи отказываются подписывать транзакции',
  pleaseAuthorize: 'Разрешите.',
  pledgeSuc: 'Арест удался.',
  pledgeFail: 'Арест не удался.',
  toBeSuccessful: 'Успех!',
  harvestSuc: 'Жатва завершена.',
  harvestFail: 'Жатва не удалась.',
  extractSuc: 'Извлечение прошло успешно.',
  extractFail: 'Извлечение не удалось.',
}
