// 韩语
export const lang = {
  name: '피자! 피자!',
  message: '이건 피자입니다.',
  home: '집',
  trade: '무역',
  exchange: '바 꿔',
  farm: '농장',
  castle: '성',
  connectPurse: '지갑 연결',
  inviteConnect: '초대장 연결',
  download: '다운로드',
  whitePaper: '백서',
  officialNews: '정부측 소식',
  // 农场
  // farm: '농장',
  raise: '유동자금통을 만들다',
  earnProfit: '돈 대신 돈을 벌어서',
  pledgeToDig: '질물로 광산을 채굴하다.',
  deposit: '입금',
  obtain: '가져오기',
  annualInterestRate: '연 이율',
  dailyProduction: '일일 생산량',
  choose: '선택',
  registered: '등록',
  RegisteredSuc: '등록 성공',
  //城堡
  dailyProduction: '일일 총생산량',
  grades: '나의 등급',
  pledge: '질 권',
  pledgePerformance: '질권 실적',
  personalPledge: '개인질권 시장가치',
  upgrade: '승급까지는 아직 멀었다',
  shareMining: '광산 건설 수익을 함께 나누다',
  addresses: '지운 주소의 수',
  a: '개',
  no: '무',
  soldiers: 'soldiers',
  knight: 'knight',
  fortress: 'fortress',
  duke: 'duke',
  general: 'general',
  king: 'king',
  queen: 'queen',
  maximum: '최대치',
  authorization: '수권',
  available: '사용 가능 한',
  extract: '추출',

  pledged: '질권 완료',
  harvestRedeem: '수확과 환매',
  pledgeToDig: '질물로 광산을 채굴하다.',
  pleaseEnter: '입력해 주세요',

  authorizationSuc: '인증 성공',
  userReject: '사용자가 서명 거부함',
  pleaseAuthorize: '먼저 권한을 부여하십시오',
  pledgeSuc: '질권설정에 성공하다',
  pledgeFail: '질권 실패',
  toBeSuccessful: '성공을 획득하다',
  harvestSuc: '수확을 거두다',
  harvestFail: '수확에 실패하다.',
  extractSuc: '추출 성공',
  extractFail: '추출 실패',
}
