// module.exports = {
//     lang:{
//         name:"小米小米",
//         message:"这是小米"
//     }
// }
// 中国
export const lang = {
  name: '披萨披萨',
  message: '这是披萨',
  home: '家',
  trade: '贸易',
  exchange: '兑换',
  farm: '农场',
  castle: '城堡',
  connectPurse: '连接钱包',
  inviteConnect: '邀请链接',
  download: '下载',
  whitePaper: '白皮书',
  officialNews: '官方消息',
  // 农场
  // farm: '农场',
  raise: '筹集流动资金池',
  earnProfit: '代币以赚取收益',
  pledgeToDig: '质押挖矿',
  deposit: '存入',
  obtain: '获取',
  annualInterestRate: '年化利率',
  dailyProduction: '每日产量',
  choose: '选择',
  registered: '注册',
  RegisteredSuc: '注册成功',
  //城堡
  dailyProduction: '每日总产量',
  grades: '我的等级',
  pledge: '质押',
  pledgePerformance: '质押业绩',
  // personalPledge: '个人质押市值',
  quantityOfPersonalPledge: '个人质押数量',
  upgrade: '距升级还差',
  shareMining: '分享挖矿收益',
  addresses: '持币地址数',
  a: '个',
  no: '无',
  soldiers: '士兵',
  knight: '骑士',
  fortress: '堡垒',
  duke: '公爵',
  general: '将军',
  king: '国王',
  queen: '皇后',
  maximum: '最大值',
  authorization: '授权',
  theAuthorization: '授权中...',
  available: '可用',
  extract: '提取',
  refundPrincipal: '退还本金',
  refundPrincipalSuc:'退还本金成功',
  refundPrincipalFail:'退还本金失败',

  pledged: '已质押',
  harvestRedeem: '收割并赎回',
  pledgeToDig: '质押挖矿',
  pleaseEnter: '请输入',

  authorizationSuc: '授权成功',
  userReject: '用户拒绝事务签名',
  pleaseAuthorize: '请先授权',
  pledgeSuc: '质押成功',
  pledgeFail: '质押失败',
  toBeSuccessful: '获取成功',
  harvestSuc: '收割成功',
  harvestFail: '收割失败',
  extractSuc: '提取成功',
  extractFail: '提取失败',
}
